/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * AptProxyRepositoriesAttributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-11T23:01:25.243+08:00")
public class AptProxyRepositoriesAttributes {
  @SerializedName("distribution")
  private String distribution = null;

  @SerializedName("flat")
  private Boolean flat = null;

  public AptProxyRepositoriesAttributes distribution(String distribution) {
    this.distribution = distribution;
    return this;
  }

   /**
   * Distribution to fetch
   * @return distribution
  **/
  @ApiModelProperty(example = "bionic", value = "Distribution to fetch")
  public String getDistribution() {
    return distribution;
  }

  public void setDistribution(String distribution) {
    this.distribution = distribution;
  }

  public AptProxyRepositoriesAttributes flat(Boolean flat) {
    this.flat = flat;
    return this;
  }

   /**
   * Whether this repository is flat
   * @return flat
  **/
  @ApiModelProperty(example = "false", required = true, value = "Whether this repository is flat")
  public Boolean isFlat() {
    return flat;
  }

  public void setFlat(Boolean flat) {
    this.flat = flat;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AptProxyRepositoriesAttributes aptProxyRepositoriesAttributes = (AptProxyRepositoriesAttributes) o;
    return Objects.equals(this.distribution, aptProxyRepositoriesAttributes.distribution) &&
        Objects.equals(this.flat, aptProxyRepositoriesAttributes.flat);
  }

  @Override
  public int hashCode() {
    return Objects.hash(distribution, flat);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AptProxyRepositoriesAttributes {\n");
    
    sb.append("    distribution: ").append(toIndentedString(distribution)).append("\n");
    sb.append("    flat: ").append(toIndentedString(flat)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

