/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.HashMap;
import java.util.List;
import java.util.Map;
import org.threeten.bp.OffsetDateTime;

/**
 * AssetXO
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-11T23:01:25.243+08:00")
public class AssetXO {
  @SerializedName("downloadUrl")
  private String downloadUrl = null;

  @SerializedName("path")
  private String path = null;

  @SerializedName("id")
  private String id = null;

  @SerializedName("repository")
  private String repository = null;

  @SerializedName("format")
  private String format = null;

  @SerializedName("checksum")
  private Map<String, Object> checksum = null;

  @SerializedName("contentType")
  private String contentType = null;

  @SerializedName("lastModified")
  private OffsetDateTime lastModified = null;

  @SerializedName("lastDownloaded")
  private OffsetDateTime lastDownloaded = null;

  @SerializedName("uploader")
  private String uploader = null;

  @SerializedName("uploaderIp")
  private String uploaderIp = null;

  @SerializedName("fileSize")
  private Long fileSize = null;

  @SerializedName("blobCreated")
  private OffsetDateTime blobCreated = null;

  public AssetXO downloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
    return this;
  }

   /**
   * Get downloadUrl
   * @return downloadUrl
  **/
  @ApiModelProperty(value = "")
  public String getDownloadUrl() {
    return downloadUrl;
  }

  public void setDownloadUrl(String downloadUrl) {
    this.downloadUrl = downloadUrl;
  }

  public AssetXO path(String path) {
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @ApiModelProperty(value = "")
  public String getPath() {
    return path;
  }

  public void setPath(String path) {
    this.path = path;
  }

  public AssetXO id(String id) {
    this.id = id;
    return this;
  }

   /**
   * Get id
   * @return id
  **/
  @ApiModelProperty(value = "")
  public String getId() {
    return id;
  }

  public void setId(String id) {
    this.id = id;
  }

  public AssetXO repository(String repository) {
    this.repository = repository;
    return this;
  }

   /**
   * Get repository
   * @return repository
  **/
  @ApiModelProperty(value = "")
  public String getRepository() {
    return repository;
  }

  public void setRepository(String repository) {
    this.repository = repository;
  }

  public AssetXO format(String format) {
    this.format = format;
    return this;
  }

   /**
   * Get format
   * @return format
  **/
  @ApiModelProperty(value = "")
  public String getFormat() {
    return format;
  }

  public void setFormat(String format) {
    this.format = format;
  }

  public AssetXO checksum(Map<String, Object> checksum) {
    this.checksum = checksum;
    return this;
  }

  public AssetXO putChecksumItem(String key, Object checksumItem) {
    if (this.checksum == null) {
      this.checksum = new HashMap<String, Object>();
    }
    this.checksum.put(key, checksumItem);
    return this;
  }

   /**
   * Get checksum
   * @return checksum
  **/
  @ApiModelProperty(value = "")
  public Map<String, Object> getChecksum() {
    return checksum;
  }

  public void setChecksum(Map<String, Object> checksum) {
    this.checksum = checksum;
  }

  public AssetXO contentType(String contentType) {
    this.contentType = contentType;
    return this;
  }

   /**
   * Get contentType
   * @return contentType
  **/
  @ApiModelProperty(value = "")
  public String getContentType() {
    return contentType;
  }

  public void setContentType(String contentType) {
    this.contentType = contentType;
  }

  public AssetXO lastModified(OffsetDateTime lastModified) {
    this.lastModified = lastModified;
    return this;
  }

   /**
   * Get lastModified
   * @return lastModified
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLastModified() {
    return lastModified;
  }

  public void setLastModified(OffsetDateTime lastModified) {
    this.lastModified = lastModified;
  }

  public AssetXO lastDownloaded(OffsetDateTime lastDownloaded) {
    this.lastDownloaded = lastDownloaded;
    return this;
  }

   /**
   * Get lastDownloaded
   * @return lastDownloaded
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getLastDownloaded() {
    return lastDownloaded;
  }

  public void setLastDownloaded(OffsetDateTime lastDownloaded) {
    this.lastDownloaded = lastDownloaded;
  }

  public AssetXO uploader(String uploader) {
    this.uploader = uploader;
    return this;
  }

   /**
   * Get uploader
   * @return uploader
  **/
  @ApiModelProperty(value = "")
  public String getUploader() {
    return uploader;
  }

  public void setUploader(String uploader) {
    this.uploader = uploader;
  }

  public AssetXO uploaderIp(String uploaderIp) {
    this.uploaderIp = uploaderIp;
    return this;
  }

   /**
   * Get uploaderIp
   * @return uploaderIp
  **/
  @ApiModelProperty(value = "")
  public String getUploaderIp() {
    return uploaderIp;
  }

  public void setUploaderIp(String uploaderIp) {
    this.uploaderIp = uploaderIp;
  }

  public AssetXO fileSize(Long fileSize) {
    this.fileSize = fileSize;
    return this;
  }

   /**
   * Get fileSize
   * @return fileSize
  **/
  @ApiModelProperty(value = "")
  public Long getFileSize() {
    return fileSize;
  }

  public void setFileSize(Long fileSize) {
    this.fileSize = fileSize;
  }

  public AssetXO blobCreated(OffsetDateTime blobCreated) {
    this.blobCreated = blobCreated;
    return this;
  }

   /**
   * Get blobCreated
   * @return blobCreated
  **/
  @ApiModelProperty(value = "")
  public OffsetDateTime getBlobCreated() {
    return blobCreated;
  }

  public void setBlobCreated(OffsetDateTime blobCreated) {
    this.blobCreated = blobCreated;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AssetXO assetXO = (AssetXO) o;
    return Objects.equals(this.downloadUrl, assetXO.downloadUrl) &&
        Objects.equals(this.path, assetXO.path) &&
        Objects.equals(this.id, assetXO.id) &&
        Objects.equals(this.repository, assetXO.repository) &&
        Objects.equals(this.format, assetXO.format) &&
        Objects.equals(this.checksum, assetXO.checksum) &&
        Objects.equals(this.contentType, assetXO.contentType) &&
        Objects.equals(this.lastModified, assetXO.lastModified) &&
        Objects.equals(this.lastDownloaded, assetXO.lastDownloaded) &&
        Objects.equals(this.uploader, assetXO.uploader) &&
        Objects.equals(this.uploaderIp, assetXO.uploaderIp) &&
        Objects.equals(this.fileSize, assetXO.fileSize) &&
        Objects.equals(this.blobCreated, assetXO.blobCreated);
  }

  @Override
  public int hashCode() {
    return Objects.hash(downloadUrl, path, id, repository, format, checksum, contentType, lastModified, lastDownloaded, uploader, uploaderIp, fileSize, blobCreated);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AssetXO {\n");
    
    sb.append("    downloadUrl: ").append(toIndentedString(downloadUrl)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    id: ").append(toIndentedString(id)).append("\n");
    sb.append("    repository: ").append(toIndentedString(repository)).append("\n");
    sb.append("    format: ").append(toIndentedString(format)).append("\n");
    sb.append("    checksum: ").append(toIndentedString(checksum)).append("\n");
    sb.append("    contentType: ").append(toIndentedString(contentType)).append("\n");
    sb.append("    lastModified: ").append(toIndentedString(lastModified)).append("\n");
    sb.append("    lastDownloaded: ").append(toIndentedString(lastDownloaded)).append("\n");
    sb.append("    uploader: ").append(toIndentedString(uploader)).append("\n");
    sb.append("    uploaderIp: ").append(toIndentedString(uploaderIp)).append("\n");
    sb.append("    fileSize: ").append(toIndentedString(fileSize)).append("\n");
    sb.append("    blobCreated: ").append(toIndentedString(blobCreated)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

