/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.AzureBlobStoreApiAuthentication;
import java.io.IOException;

/**
 * AzureBlobStoreApiBucketConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-11T23:01:25.243+08:00")
public class AzureBlobStoreApiBucketConfiguration {
  @SerializedName("accountName")
  private String accountName = null;

  @SerializedName("containerName")
  private String containerName = null;

  @SerializedName("authentication")
  private AzureBlobStoreApiAuthentication authentication = null;

  public AzureBlobStoreApiBucketConfiguration accountName(String accountName) {
    this.accountName = accountName;
    return this;
  }

   /**
   * Account name found under Access keys for the storage account.
   * @return accountName
  **/
  @ApiModelProperty(required = true, value = "Account name found under Access keys for the storage account.")
  public String getAccountName() {
    return accountName;
  }

  public void setAccountName(String accountName) {
    this.accountName = accountName;
  }

  public AzureBlobStoreApiBucketConfiguration containerName(String containerName) {
    this.containerName = containerName;
    return this;
  }

   /**
   * The name of an existing container to be used for storage.
   * @return containerName
  **/
  @ApiModelProperty(required = true, value = "The name of an existing container to be used for storage.")
  public String getContainerName() {
    return containerName;
  }

  public void setContainerName(String containerName) {
    this.containerName = containerName;
  }

  public AzureBlobStoreApiBucketConfiguration authentication(AzureBlobStoreApiAuthentication authentication) {
    this.authentication = authentication;
    return this;
  }

   /**
   * The Azure specific authentication details.
   * @return authentication
  **/
  @ApiModelProperty(required = true, value = "The Azure specific authentication details.")
  public AzureBlobStoreApiAuthentication getAuthentication() {
    return authentication;
  }

  public void setAuthentication(AzureBlobStoreApiAuthentication authentication) {
    this.authentication = authentication;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AzureBlobStoreApiBucketConfiguration azureBlobStoreApiBucketConfiguration = (AzureBlobStoreApiBucketConfiguration) o;
    return Objects.equals(this.accountName, azureBlobStoreApiBucketConfiguration.accountName) &&
        Objects.equals(this.containerName, azureBlobStoreApiBucketConfiguration.containerName) &&
        Objects.equals(this.authentication, azureBlobStoreApiBucketConfiguration.authentication);
  }

  @Override
  public int hashCode() {
    return Objects.hash(accountName, containerName, authentication);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AzureBlobStoreApiBucketConfiguration {\n");
    
    sb.append("    accountName: ").append(toIndentedString(accountName)).append("\n");
    sb.append("    containerName: ").append(toIndentedString(containerName)).append("\n");
    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

