/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * BowerAttributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-11T23:01:25.243+08:00")
public class BowerAttributes {
  @SerializedName("rewritePackageUrls")
  private Boolean rewritePackageUrls = null;

  public BowerAttributes rewritePackageUrls(Boolean rewritePackageUrls) {
    this.rewritePackageUrls = rewritePackageUrls;
    return this;
  }

   /**
   * Whether to force Bower to retrieve packages through this proxy repository
   * @return rewritePackageUrls
  **/
  @ApiModelProperty(example = "true", required = true, value = "Whether to force Bower to retrieve packages through this proxy repository")
  public Boolean isRewritePackageUrls() {
    return rewritePackageUrls;
  }

  public void setRewritePackageUrls(Boolean rewritePackageUrls) {
    this.rewritePackageUrls = rewritePackageUrls;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BowerAttributes bowerAttributes = (BowerAttributes) o;
    return Objects.equals(this.rewritePackageUrls, bowerAttributes.rewritePackageUrls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(rewritePackageUrls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BowerAttributes {\n");
    
    sb.append("    rewritePackageUrls: ").append(toIndentedString(rewritePackageUrls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

