/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ComponentAttributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-11T23:01:25.243+08:00")
public class ComponentAttributes {
  @SerializedName("proprietaryComponents")
  private Boolean proprietaryComponents = null;

  public ComponentAttributes proprietaryComponents(Boolean proprietaryComponents) {
    this.proprietaryComponents = proprietaryComponents;
    return this;
  }

   /**
   * Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Firewall)
   * @return proprietaryComponents
  **/
  @ApiModelProperty(value = "Components in this repository count as proprietary for namespace conflict attacks (requires Sonatype Nexus Firewall)")
  public Boolean isProprietaryComponents() {
    return proprietaryComponents;
  }

  public void setProprietaryComponents(Boolean proprietaryComponents) {
    this.proprietaryComponents = proprietaryComponents;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ComponentAttributes componentAttributes = (ComponentAttributes) o;
    return Objects.equals(this.proprietaryComponents, componentAttributes.proprietaryComponents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(proprietaryComponents);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ComponentAttributes {\n");
    
    sb.append("    proprietaryComponents: ").append(toIndentedString(proprietaryComponents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

