/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.HttpClientConnectionAttributes;
import io.swagger.client.model.HttpClientConnectionAuthenticationAttributesWithPreemptive;
import java.io.IOException;

/**
 * HttpClientAttributesWithPreemptiveAuth
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-11T23:01:25.243+08:00")
public class HttpClientAttributesWithPreemptiveAuth {
  @SerializedName("blocked")
  private Boolean blocked = null;

  @SerializedName("autoBlock")
  private Boolean autoBlock = null;

  @SerializedName("connection")
  private HttpClientConnectionAttributes connection = null;

  @SerializedName("authentication")
  private HttpClientConnectionAuthenticationAttributesWithPreemptive authentication = null;

  public HttpClientAttributesWithPreemptiveAuth blocked(Boolean blocked) {
    this.blocked = blocked;
    return this;
  }

   /**
   * Whether to block outbound connections on the repository
   * @return blocked
  **/
  @ApiModelProperty(example = "false", required = true, value = "Whether to block outbound connections on the repository")
  public Boolean isBlocked() {
    return blocked;
  }

  public void setBlocked(Boolean blocked) {
    this.blocked = blocked;
  }

  public HttpClientAttributesWithPreemptiveAuth autoBlock(Boolean autoBlock) {
    this.autoBlock = autoBlock;
    return this;
  }

   /**
   * Whether to auto-block outbound connections if remote peer is detected as unreachable/unresponsive
   * @return autoBlock
  **/
  @ApiModelProperty(example = "true", required = true, value = "Whether to auto-block outbound connections if remote peer is detected as unreachable/unresponsive")
  public Boolean isAutoBlock() {
    return autoBlock;
  }

  public void setAutoBlock(Boolean autoBlock) {
    this.autoBlock = autoBlock;
  }

  public HttpClientAttributesWithPreemptiveAuth connection(HttpClientConnectionAttributes connection) {
    this.connection = connection;
    return this;
  }

   /**
   * Get connection
   * @return connection
  **/
  @ApiModelProperty(value = "")
  public HttpClientConnectionAttributes getConnection() {
    return connection;
  }

  public void setConnection(HttpClientConnectionAttributes connection) {
    this.connection = connection;
  }

  public HttpClientAttributesWithPreemptiveAuth authentication(HttpClientConnectionAuthenticationAttributesWithPreemptive authentication) {
    this.authentication = authentication;
    return this;
  }

   /**
   * Get authentication
   * @return authentication
  **/
  @ApiModelProperty(value = "")
  public HttpClientConnectionAuthenticationAttributesWithPreemptive getAuthentication() {
    return authentication;
  }

  public void setAuthentication(HttpClientConnectionAuthenticationAttributesWithPreemptive authentication) {
    this.authentication = authentication;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    HttpClientAttributesWithPreemptiveAuth httpClientAttributesWithPreemptiveAuth = (HttpClientAttributesWithPreemptiveAuth) o;
    return Objects.equals(this.blocked, httpClientAttributesWithPreemptiveAuth.blocked) &&
        Objects.equals(this.autoBlock, httpClientAttributesWithPreemptiveAuth.autoBlock) &&
        Objects.equals(this.connection, httpClientAttributesWithPreemptiveAuth.connection) &&
        Objects.equals(this.authentication, httpClientAttributesWithPreemptiveAuth.authentication);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blocked, autoBlock, connection, authentication);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class HttpClientAttributesWithPreemptiveAuth {\n");
    
    sb.append("    blocked: ").append(toIndentedString(blocked)).append("\n");
    sb.append("    autoBlock: ").append(toIndentedString(autoBlock)).append("\n");
    sb.append("    connection: ").append(toIndentedString(connection)).append("\n");
    sb.append("    authentication: ").append(toIndentedString(authentication)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

