/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * PyPiProxyAttributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-11T23:01:25.243+08:00")
public class PyPiProxyAttributes {
  @SerializedName("removeQuarantined")
  private Boolean removeQuarantined = null;

  public PyPiProxyAttributes removeQuarantined(Boolean removeQuarantined) {
    this.removeQuarantined = removeQuarantined;
    return this;
  }

   /**
   * Remove Quarantined Versions
   * @return removeQuarantined
  **/
  @ApiModelProperty(example = "true", required = true, value = "Remove Quarantined Versions")
  public Boolean isRemoveQuarantined() {
    return removeQuarantined;
  }

  public void setRemoveQuarantined(Boolean removeQuarantined) {
    this.removeQuarantined = removeQuarantined;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PyPiProxyAttributes pyPiProxyAttributes = (PyPiProxyAttributes) o;
    return Objects.equals(this.removeQuarantined, pyPiProxyAttributes.removeQuarantined);
  }

  @Override
  public int hashCode() {
    return Objects.hash(removeQuarantined);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PyPiProxyAttributes {\n");
    
    sb.append("    removeQuarantined: ").append(toIndentedString(removeQuarantined)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

