/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * ReplicationAttributes
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-11T23:01:25.243+08:00")
public class ReplicationAttributes {
  @SerializedName("preemptivePullEnabled")
  private Boolean preemptivePullEnabled = null;

  @SerializedName("assetPathRegex")
  private String assetPathRegex = null;

  public ReplicationAttributes preemptivePullEnabled(Boolean preemptivePullEnabled) {
    this.preemptivePullEnabled = preemptivePullEnabled;
    return this;
  }

   /**
   * Whether pre-emptive pull is enabled
   * @return preemptivePullEnabled
  **/
  @ApiModelProperty(example = "false", required = true, value = "Whether pre-emptive pull is enabled")
  public Boolean isPreemptivePullEnabled() {
    return preemptivePullEnabled;
  }

  public void setPreemptivePullEnabled(Boolean preemptivePullEnabled) {
    this.preemptivePullEnabled = preemptivePullEnabled;
  }

  public ReplicationAttributes assetPathRegex(String assetPathRegex) {
    this.assetPathRegex = assetPathRegex;
    return this;
  }

   /**
   * Regular Expression of Asset Paths to pull pre-emptively pull
   * @return assetPathRegex
  **/
  @ApiModelProperty(value = "Regular Expression of Asset Paths to pull pre-emptively pull")
  public String getAssetPathRegex() {
    return assetPathRegex;
  }

  public void setAssetPathRegex(String assetPathRegex) {
    this.assetPathRegex = assetPathRegex;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ReplicationAttributes replicationAttributes = (ReplicationAttributes) o;
    return Objects.equals(this.preemptivePullEnabled, replicationAttributes.preemptivePullEnabled) &&
        Objects.equals(this.assetPathRegex, replicationAttributes.assetPathRegex);
  }

  @Override
  public int hashCode() {
    return Objects.hash(preemptivePullEnabled, assetPathRegex);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ReplicationAttributes {\n");
    
    sb.append("    preemptivePullEnabled: ").append(toIndentedString(preemptivePullEnabled)).append("\n");
    sb.append("    assetPathRegex: ").append(toIndentedString(assetPathRegex)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

