/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.S3BlobStoreApiAdvancedBucketConnection;
import io.swagger.client.model.S3BlobStoreApiBucket;
import io.swagger.client.model.S3BlobStoreApiBucketSecurity;
import io.swagger.client.model.S3BlobStoreApiEncryption;
import java.io.IOException;

/**
 * S3BlobStoreApiBucketConfiguration
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-11T23:01:25.243+08:00")
public class S3BlobStoreApiBucketConfiguration {
  @SerializedName("bucket")
  private S3BlobStoreApiBucket bucket = null;

  @SerializedName("encryption")
  private S3BlobStoreApiEncryption encryption = null;

  @SerializedName("bucketSecurity")
  private S3BlobStoreApiBucketSecurity bucketSecurity = null;

  @SerializedName("advancedBucketConnection")
  private S3BlobStoreApiAdvancedBucketConnection advancedBucketConnection = null;

   /**
   * Details of the S3 bucket such as name and region
   * @return bucket
  **/
  @ApiModelProperty(required = true, value = "Details of the S3 bucket such as name and region")
  public S3BlobStoreApiBucket getBucket() {
    return bucket;
  }

   /**
   * The type of encryption to use if any
   * @return encryption
  **/
  @ApiModelProperty(value = "The type of encryption to use if any")
  public S3BlobStoreApiEncryption getEncryption() {
    return encryption;
  }

  public S3BlobStoreApiBucketConfiguration bucketSecurity(S3BlobStoreApiBucketSecurity bucketSecurity) {
    this.bucketSecurity = bucketSecurity;
    return this;
  }

   /**
   * Security details for granting access the S3 API
   * @return bucketSecurity
  **/
  @ApiModelProperty(value = "Security details for granting access the S3 API")
  public S3BlobStoreApiBucketSecurity getBucketSecurity() {
    return bucketSecurity;
  }

  public void setBucketSecurity(S3BlobStoreApiBucketSecurity bucketSecurity) {
    this.bucketSecurity = bucketSecurity;
  }

  public S3BlobStoreApiBucketConfiguration advancedBucketConnection(S3BlobStoreApiAdvancedBucketConnection advancedBucketConnection) {
    this.advancedBucketConnection = advancedBucketConnection;
    return this;
  }

   /**
   * A custom endpoint URL, signer type and whether path style access is enabled
   * @return advancedBucketConnection
  **/
  @ApiModelProperty(value = "A custom endpoint URL, signer type and whether path style access is enabled")
  public S3BlobStoreApiAdvancedBucketConnection getAdvancedBucketConnection() {
    return advancedBucketConnection;
  }

  public void setAdvancedBucketConnection(S3BlobStoreApiAdvancedBucketConnection advancedBucketConnection) {
    this.advancedBucketConnection = advancedBucketConnection;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    S3BlobStoreApiBucketConfiguration s3BlobStoreApiBucketConfiguration = (S3BlobStoreApiBucketConfiguration) o;
    return Objects.equals(this.bucket, s3BlobStoreApiBucketConfiguration.bucket) &&
        Objects.equals(this.encryption, s3BlobStoreApiBucketConfiguration.encryption) &&
        Objects.equals(this.bucketSecurity, s3BlobStoreApiBucketConfiguration.bucketSecurity) &&
        Objects.equals(this.advancedBucketConnection, s3BlobStoreApiBucketConfiguration.advancedBucketConnection);
  }

  @Override
  public int hashCode() {
    return Objects.hash(bucket, encryption, bucketSecurity, advancedBucketConnection);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class S3BlobStoreApiBucketConfiguration {\n");
    
    sb.append("    bucket: ").append(toIndentedString(bucket)).append("\n");
    sb.append("    encryption: ").append(toIndentedString(encryption)).append("\n");
    sb.append("    bucketSecurity: ").append(toIndentedString(bucketSecurity)).append("\n");
    sb.append("    advancedBucketConnection: ").append(toIndentedString(advancedBucketConnection)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

