/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * SupportZipGeneratorRequest
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-11T23:01:25.243+08:00")
public class SupportZipGeneratorRequest {
  @SerializedName("systemInformation")
  private Boolean systemInformation = null;

  @SerializedName("threadDump")
  private Boolean threadDump = null;

  @SerializedName("metrics")
  private Boolean metrics = null;

  @SerializedName("configuration")
  private Boolean _configuration = null;

  @SerializedName("security")
  private Boolean security = null;

  @SerializedName("log")
  private Boolean log = null;

  @SerializedName("taskLog")
  private Boolean taskLog = null;

  @SerializedName("auditLog")
  private Boolean auditLog = null;

  @SerializedName("jmx")
  private Boolean jmx = null;

  @SerializedName("replication")
  private Boolean replication = null;

  @SerializedName("limitFileSizes")
  private Boolean limitFileSizes = null;

  @SerializedName("limitZipSize")
  private Boolean limitZipSize = null;

  @SerializedName("hostname")
  private String hostname = null;

  public SupportZipGeneratorRequest systemInformation(Boolean systemInformation) {
    this.systemInformation = systemInformation;
    return this;
  }

   /**
   * Get systemInformation
   * @return systemInformation
  **/
  @ApiModelProperty(value = "")
  public Boolean isSystemInformation() {
    return systemInformation;
  }

  public void setSystemInformation(Boolean systemInformation) {
    this.systemInformation = systemInformation;
  }

  public SupportZipGeneratorRequest threadDump(Boolean threadDump) {
    this.threadDump = threadDump;
    return this;
  }

   /**
   * Get threadDump
   * @return threadDump
  **/
  @ApiModelProperty(value = "")
  public Boolean isThreadDump() {
    return threadDump;
  }

  public void setThreadDump(Boolean threadDump) {
    this.threadDump = threadDump;
  }

  public SupportZipGeneratorRequest metrics(Boolean metrics) {
    this.metrics = metrics;
    return this;
  }

   /**
   * Get metrics
   * @return metrics
  **/
  @ApiModelProperty(value = "")
  public Boolean isMetrics() {
    return metrics;
  }

  public void setMetrics(Boolean metrics) {
    this.metrics = metrics;
  }

  public SupportZipGeneratorRequest _configuration(Boolean _configuration) {
    this._configuration = _configuration;
    return this;
  }

   /**
   * Get _configuration
   * @return _configuration
  **/
  @ApiModelProperty(value = "")
  public Boolean isConfiguration() {
    return _configuration;
  }

  public void setConfiguration(Boolean _configuration) {
    this._configuration = _configuration;
  }

  public SupportZipGeneratorRequest security(Boolean security) {
    this.security = security;
    return this;
  }

   /**
   * Get security
   * @return security
  **/
  @ApiModelProperty(value = "")
  public Boolean isSecurity() {
    return security;
  }

  public void setSecurity(Boolean security) {
    this.security = security;
  }

  public SupportZipGeneratorRequest log(Boolean log) {
    this.log = log;
    return this;
  }

   /**
   * Get log
   * @return log
  **/
  @ApiModelProperty(value = "")
  public Boolean isLog() {
    return log;
  }

  public void setLog(Boolean log) {
    this.log = log;
  }

  public SupportZipGeneratorRequest taskLog(Boolean taskLog) {
    this.taskLog = taskLog;
    return this;
  }

   /**
   * Get taskLog
   * @return taskLog
  **/
  @ApiModelProperty(value = "")
  public Boolean isTaskLog() {
    return taskLog;
  }

  public void setTaskLog(Boolean taskLog) {
    this.taskLog = taskLog;
  }

  public SupportZipGeneratorRequest auditLog(Boolean auditLog) {
    this.auditLog = auditLog;
    return this;
  }

   /**
   * Get auditLog
   * @return auditLog
  **/
  @ApiModelProperty(value = "")
  public Boolean isAuditLog() {
    return auditLog;
  }

  public void setAuditLog(Boolean auditLog) {
    this.auditLog = auditLog;
  }

  public SupportZipGeneratorRequest jmx(Boolean jmx) {
    this.jmx = jmx;
    return this;
  }

   /**
   * Get jmx
   * @return jmx
  **/
  @ApiModelProperty(value = "")
  public Boolean isJmx() {
    return jmx;
  }

  public void setJmx(Boolean jmx) {
    this.jmx = jmx;
  }

  public SupportZipGeneratorRequest replication(Boolean replication) {
    this.replication = replication;
    return this;
  }

   /**
   * Get replication
   * @return replication
  **/
  @ApiModelProperty(value = "")
  public Boolean isReplication() {
    return replication;
  }

  public void setReplication(Boolean replication) {
    this.replication = replication;
  }

  public SupportZipGeneratorRequest limitFileSizes(Boolean limitFileSizes) {
    this.limitFileSizes = limitFileSizes;
    return this;
  }

   /**
   * Get limitFileSizes
   * @return limitFileSizes
  **/
  @ApiModelProperty(value = "")
  public Boolean isLimitFileSizes() {
    return limitFileSizes;
  }

  public void setLimitFileSizes(Boolean limitFileSizes) {
    this.limitFileSizes = limitFileSizes;
  }

  public SupportZipGeneratorRequest limitZipSize(Boolean limitZipSize) {
    this.limitZipSize = limitZipSize;
    return this;
  }

   /**
   * Get limitZipSize
   * @return limitZipSize
  **/
  @ApiModelProperty(value = "")
  public Boolean isLimitZipSize() {
    return limitZipSize;
  }

  public void setLimitZipSize(Boolean limitZipSize) {
    this.limitZipSize = limitZipSize;
  }

  public SupportZipGeneratorRequest hostname(String hostname) {
    this.hostname = hostname;
    return this;
  }

   /**
   * Get hostname
   * @return hostname
  **/
  @ApiModelProperty(value = "")
  public String getHostname() {
    return hostname;
  }

  public void setHostname(String hostname) {
    this.hostname = hostname;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    SupportZipGeneratorRequest supportZipGeneratorRequest = (SupportZipGeneratorRequest) o;
    return Objects.equals(this.systemInformation, supportZipGeneratorRequest.systemInformation) &&
        Objects.equals(this.threadDump, supportZipGeneratorRequest.threadDump) &&
        Objects.equals(this.metrics, supportZipGeneratorRequest.metrics) &&
        Objects.equals(this._configuration, supportZipGeneratorRequest._configuration) &&
        Objects.equals(this.security, supportZipGeneratorRequest.security) &&
        Objects.equals(this.log, supportZipGeneratorRequest.log) &&
        Objects.equals(this.taskLog, supportZipGeneratorRequest.taskLog) &&
        Objects.equals(this.auditLog, supportZipGeneratorRequest.auditLog) &&
        Objects.equals(this.jmx, supportZipGeneratorRequest.jmx) &&
        Objects.equals(this.replication, supportZipGeneratorRequest.replication) &&
        Objects.equals(this.limitFileSizes, supportZipGeneratorRequest.limitFileSizes) &&
        Objects.equals(this.limitZipSize, supportZipGeneratorRequest.limitZipSize) &&
        Objects.equals(this.hostname, supportZipGeneratorRequest.hostname);
  }

  @Override
  public int hashCode() {
    return Objects.hash(systemInformation, threadDump, metrics, _configuration, security, log, taskLog, auditLog, jmx, replication, limitFileSizes, limitZipSize, hostname);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class SupportZipGeneratorRequest {\n");
    
    sb.append("    systemInformation: ").append(toIndentedString(systemInformation)).append("\n");
    sb.append("    threadDump: ").append(toIndentedString(threadDump)).append("\n");
    sb.append("    metrics: ").append(toIndentedString(metrics)).append("\n");
    sb.append("    _configuration: ").append(toIndentedString(_configuration)).append("\n");
    sb.append("    security: ").append(toIndentedString(security)).append("\n");
    sb.append("    log: ").append(toIndentedString(log)).append("\n");
    sb.append("    taskLog: ").append(toIndentedString(taskLog)).append("\n");
    sb.append("    auditLog: ").append(toIndentedString(auditLog)).append("\n");
    sb.append("    jmx: ").append(toIndentedString(jmx)).append("\n");
    sb.append("    replication: ").append(toIndentedString(replication)).append("\n");
    sb.append("    limitFileSizes: ").append(toIndentedString(limitFileSizes)).append("\n");
    sb.append("    limitZipSize: ").append(toIndentedString(limitZipSize)).append("\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

