/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.model;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import io.swagger.client.model.CleanupPolicyAttributes;
import io.swagger.client.model.ComponentAttributes;
import io.swagger.client.model.HostedStorageAttributes;
import io.swagger.client.model.YumAttributes;
import java.io.IOException;

/**
 * YumHostedApiRepository
 */
@javax.annotation.Generated(value = "io.swagger.codegen.languages.JavaClientCodegen", date = "2023-12-11T23:01:25.243+08:00")
public class YumHostedApiRepository {
  @SerializedName("name")
  private String name = null;

  @SerializedName("online")
  private Boolean online = null;

  @SerializedName("storage")
  private HostedStorageAttributes storage = null;

  @SerializedName("cleanup")
  private CleanupPolicyAttributes cleanup = null;

  @SerializedName("component")
  private ComponentAttributes component = null;

  @SerializedName("yum")
  private YumAttributes yum = null;

  public YumHostedApiRepository name(String name) {
    this.name = name;
    return this;
  }

   /**
   * A unique identifier for this repository
   * @return name
  **/
  @ApiModelProperty(example = "internal", value = "A unique identifier for this repository")
  public String getName() {
    return name;
  }

  public void setName(String name) {
    this.name = name;
  }

  public YumHostedApiRepository online(Boolean online) {
    this.online = online;
    return this;
  }

   /**
   * Whether this repository accepts incoming requests
   * @return online
  **/
  @ApiModelProperty(example = "true", required = true, value = "Whether this repository accepts incoming requests")
  public Boolean isOnline() {
    return online;
  }

  public void setOnline(Boolean online) {
    this.online = online;
  }

  public YumHostedApiRepository storage(HostedStorageAttributes storage) {
    this.storage = storage;
    return this;
  }

   /**
   * Get storage
   * @return storage
  **/
  @ApiModelProperty(required = true, value = "")
  public HostedStorageAttributes getStorage() {
    return storage;
  }

  public void setStorage(HostedStorageAttributes storage) {
    this.storage = storage;
  }

  public YumHostedApiRepository cleanup(CleanupPolicyAttributes cleanup) {
    this.cleanup = cleanup;
    return this;
  }

   /**
   * Get cleanup
   * @return cleanup
  **/
  @ApiModelProperty(value = "")
  public CleanupPolicyAttributes getCleanup() {
    return cleanup;
  }

  public void setCleanup(CleanupPolicyAttributes cleanup) {
    this.cleanup = cleanup;
  }

  public YumHostedApiRepository component(ComponentAttributes component) {
    this.component = component;
    return this;
  }

   /**
   * Get component
   * @return component
  **/
  @ApiModelProperty(value = "")
  public ComponentAttributes getComponent() {
    return component;
  }

  public void setComponent(ComponentAttributes component) {
    this.component = component;
  }

  public YumHostedApiRepository yum(YumAttributes yum) {
    this.yum = yum;
    return this;
  }

   /**
   * Get yum
   * @return yum
  **/
  @ApiModelProperty(required = true, value = "")
  public YumAttributes getYum() {
    return yum;
  }

  public void setYum(YumAttributes yum) {
    this.yum = yum;
  }


  @Override
  public boolean equals(java.lang.Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    YumHostedApiRepository yumHostedApiRepository = (YumHostedApiRepository) o;
    return Objects.equals(this.name, yumHostedApiRepository.name) &&
        Objects.equals(this.online, yumHostedApiRepository.online) &&
        Objects.equals(this.storage, yumHostedApiRepository.storage) &&
        Objects.equals(this.cleanup, yumHostedApiRepository.cleanup) &&
        Objects.equals(this.component, yumHostedApiRepository.component) &&
        Objects.equals(this.yum, yumHostedApiRepository.yum);
  }

  @Override
  public int hashCode() {
    return Objects.hash(name, online, storage, cleanup, component, yum);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class YumHostedApiRepository {\n");
    
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("    online: ").append(toIndentedString(online)).append("\n");
    sb.append("    storage: ").append(toIndentedString(storage)).append("\n");
    sb.append("    cleanup: ").append(toIndentedString(cleanup)).append("\n");
    sb.append("    component: ").append(toIndentedString(component)).append("\n");
    sb.append("    yum: ").append(toIndentedString(yum)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(java.lang.Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

