/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.AssetXO;
import io.swagger.client.model.PageAssetXO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for AssetsApi
 */
@Ignore
public class AssetsApiTest {

    private final AssetsApi api = new AssetsApi();

    
    /**
     * Delete a single asset
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteAssetTest() throws Exception {
        String id = null;
        api.deleteAsset(id);

        // TODO: test validations
    }
    
    /**
     * Get a single asset
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAssetByIdTest() throws Exception {
        String id = null;
        AssetXO response = api.getAssetById(id);

        // TODO: test validations
    }
    
    /**
     * List assets
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getAssetsTest() throws Exception {
        String repository = null;
        String continuationToken = null;
        PageAssetXO response = api.getAssets(repository, continuationToken);

        // TODO: test validations
    }
    
}
