/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.AzureBlobStoreApiModel;
import io.swagger.client.model.BlobStoreQuotaResultXO;
import io.swagger.client.model.FileBlobStoreApiCreateRequest;
import io.swagger.client.model.FileBlobStoreApiModel;
import io.swagger.client.model.FileBlobStoreApiUpdateRequest;
import io.swagger.client.model.GenericBlobStoreApiResponse;
import io.swagger.client.model.S3BlobStoreApiModel;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for BlobStoreApi
 */
@Ignore
public class BlobStoreApiTest {

    private final BlobStoreApi api = new BlobStoreApi();

    
    /**
     * Create an S3 blob store
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createBlobStoreTest() throws Exception {
        S3BlobStoreApiModel body = null;
        api.createBlobStore(body);

        // TODO: test validations
    }
    
    /**
     * Create an Azure blob store
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createBlobStore1Test() throws Exception {
        AzureBlobStoreApiModel body = null;
        api.createBlobStore1(body);

        // TODO: test validations
    }
    
    /**
     * Create a file blob store
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createFileBlobStoreTest() throws Exception {
        FileBlobStoreApiCreateRequest body = null;
        api.createFileBlobStore(body);

        // TODO: test validations
    }
    
    /**
     * Delete a blob store by name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteBlobStoreTest() throws Exception {
        String name = null;
        api.deleteBlobStore(name);

        // TODO: test validations
    }
    
    /**
     * Get a S3 blob store configuration by name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getBlobStoreTest() throws Exception {
        String name = null;
        S3BlobStoreApiModel response = api.getBlobStore(name);

        // TODO: test validations
    }
    
    /**
     * Get an Azure blob store configuration by name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getBlobStore1Test() throws Exception {
        String name = null;
        AzureBlobStoreApiModel response = api.getBlobStore1(name);

        // TODO: test validations
    }
    
    /**
     * Get a file blob store configuration by name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getFileBlobStoreConfigurationTest() throws Exception {
        String name = null;
        FileBlobStoreApiModel response = api.getFileBlobStoreConfiguration(name);

        // TODO: test validations
    }
    
    /**
     * List the blob stores
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void listBlobStoresTest() throws Exception {
        List<GenericBlobStoreApiResponse> response = api.listBlobStores();

        // TODO: test validations
    }
    
    /**
     * Get quota status for a given blob store
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void quotaStatusTest() throws Exception {
        String name = null;
        BlobStoreQuotaResultXO response = api.quotaStatus(name);

        // TODO: test validations
    }
    
    /**
     * Update an S3 blob store configuration by name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateBlobStoreTest() throws Exception {
        String name = null;
        S3BlobStoreApiModel body = null;
        api.updateBlobStore(name, body);

        // TODO: test validations
    }
    
    /**
     * Update an Azure blob store configuration by name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateBlobStore1Test() throws Exception {
        String name = null;
        AzureBlobStoreApiModel body = null;
        api.updateBlobStore1(name, body);

        // TODO: test validations
    }
    
    /**
     * Update a file blob store configuration by name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateFileBlobStoreTest() throws Exception {
        String name = null;
        FileBlobStoreApiUpdateRequest body = null;
        api.updateFileBlobStore(name, body);

        // TODO: test validations
    }
    
}
