/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.ContentSelectorApiCreateRequest;
import io.swagger.client.model.ContentSelectorApiResponse;
import io.swagger.client.model.ContentSelectorApiUpdateRequest;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ContentSelectorsApi
 */
@Ignore
public class ContentSelectorsApiTest {

    private final ContentSelectorsApi api = new ContentSelectorsApi();

    
    /**
     * Create a new content selector
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createContentSelectorTest() throws Exception {
        ContentSelectorApiCreateRequest body = null;
        api.createContentSelector(body);

        // TODO: test validations
    }
    
    /**
     * Delete a content selector
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteContentSelectorTest() throws Exception {
        String name = null;
        api.deleteContentSelector(name);

        // TODO: test validations
    }
    
    /**
     * Get a content selector by name
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getContentSelectorTest() throws Exception {
        String name = null;
        ContentSelectorApiResponse response = api.getContentSelector(name);

        // TODO: test validations
    }
    
    /**
     * List content selectors
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getContentSelectorsTest() throws Exception {
        List<ContentSelectorApiResponse> response = api.getContentSelectors();

        // TODO: test validations
    }
    
    /**
     * Update a content selector
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateContentSelectorTest() throws Exception {
        String name = null;
        ContentSelectorApiUpdateRequest body = null;
        api.updateContentSelector(name, body);

        // TODO: test validations
    }
    
}
