/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.ApiEmailConfiguration;
import io.swagger.client.model.ApiEmailValidation;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for EmailApi
 */
@Ignore
public class EmailApiTest {

    private final EmailApi api = new EmailApi();

    
    /**
     * Disable and clear the email configuration
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteEmailConfigurationTest() throws Exception {
        api.deleteEmailConfiguration();

        // TODO: test validations
    }
    
    /**
     * Retrieve the current email configuration
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getEmailConfigurationTest() throws Exception {
        ApiEmailConfiguration response = api.getEmailConfiguration();

        // TODO: test validations
    }
    
    /**
     * Set the current email configuration
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void setEmailConfigurationTest() throws Exception {
        ApiEmailConfiguration body = null;
        api.setEmailConfiguration(body);

        // TODO: test validations
    }
    
    /**
     * Send a test email to the email address provided in the request body
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void testEmailConfigurationTest() throws Exception {
        String body = null;
        ApiEmailValidation response = api.testEmailConfiguration(body);

        // TODO: test validations
    }
    
}
