/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.IqConnectionXo;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for ManageSonatypeRepositoryFirewallConfigurationApi
 */
@Ignore
public class ManageSonatypeRepositoryFirewallConfigurationApiTest {

    private final ManageSonatypeRepositoryFirewallConfigurationApi api = new ManageSonatypeRepositoryFirewallConfigurationApi();

    
    /**
     * Disable Sonatype Repository Firewall
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void disableIqTest() throws Exception {
        api.disableIq();

        // TODO: test validations
    }
    
    /**
     * Enable Sonatype Repository Firewall
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void enableIqTest() throws Exception {
        api.enableIq();

        // TODO: test validations
    }
    
    /**
     * Get Sonatype Repository Firewall configuration
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getConfigurationTest() throws Exception {
        api.getConfiguration();

        // TODO: test validations
    }
    
    /**
     * Update Sonatype Repository Firewall configuration
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateConfigurationTest() throws Exception {
        IqConnectionXo body = null;
        api.updateConfiguration(body);

        // TODO: test validations
    }
    
    /**
     * Verify Sonatype Repository Firewall connection
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void verifyConnectionTest() throws Exception {
        api.verifyConnection();

        // TODO: test validations
    }
    
}
