/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.ApiUserSource;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecurityManagementApi
 */
@Ignore
public class SecurityManagementApiTest {

    private final SecurityManagementApi api = new SecurityManagementApi();

    
    /**
     * Retrieve a list of the available user sources.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUserSourcesTest() throws Exception {
        List<ApiUserSource> response = api.getUserSources();

        // TODO: test validations
    }
    
}
