/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.ApiCreateUser;
import io.swagger.client.model.ApiUser;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecurityManagementUsersApi
 */
@Ignore
public class SecurityManagementUsersApiTest {

    private final SecurityManagementUsersApi api = new SecurityManagementUsersApi();

    
    /**
     * Change a user&#39;s password.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void changePasswordTest() throws Exception {
        String userId = null;
        String body = null;
        api.changePassword(userId, body);

        // TODO: test validations
    }
    
    /**
     * Create a new user in the default source.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void createUserTest() throws Exception {
        ApiCreateUser body = null;
        ApiUser response = api.createUser(body);

        // TODO: test validations
    }
    
    /**
     * Delete a user.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void deleteUserTest() throws Exception {
        String userId = null;
        api.deleteUser(userId);

        // TODO: test validations
    }
    
    /**
     * Retrieve a list of users. Note if the source is not &#39;default&#39; the response is limited to 100 users.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getUsersTest() throws Exception {
        String userId = null;
        String source = null;
        List<ApiUser> response = api.getUsers(userId, source);

        // TODO: test validations
    }
    
    /**
     * Update an existing user.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void updateUserTest() throws Exception {
        String userId = null;
        ApiUser body = null;
        api.updateUser(userId, body);

        // TODO: test validations
    }
    
}
