/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.ApiCertificate;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SecurityCertificatesApi
 */
@Ignore
public class SecurityCertificatesApiTest {

    private final SecurityCertificatesApi api = new SecurityCertificatesApi();

    
    /**
     * Add a certificate to the trust store.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void addCertificateTest() throws Exception {
        String body = null;
        ApiCertificate response = api.addCertificate(body);

        // TODO: test validations
    }
    
    /**
     * Retrieve a list of certificates added to the trust store.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void getTrustStoreCertificatesTest() throws Exception {
        List<ApiCertificate> response = api.getTrustStoreCertificates();

        // TODO: test validations
    }
    
    /**
     * Remove a certificate in the trust store.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void removeCertificateTest() throws Exception {
        String id = null;
        api.removeCertificate(id);

        // TODO: test validations
    }
    
    /**
     * Helper method to retrieve certificate details from a remote system.
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void retrieveCertificateTest() throws Exception {
        String host = null;
        Integer port = null;
        String protocolHint = null;
        ApiCertificate response = api.retrieveCertificate(host, port, protocolHint);

        // TODO: test validations
    }
    
}
