/*
 * Nexus Repository Manager REST API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 3.63.0-01
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */


package io.swagger.client.api;

import io.swagger.client.model.SupportZipGeneratorRequest;
import io.swagger.client.model.SupportZipXO;
import org.junit.Test;
import org.junit.Ignore;


import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * API tests for SupportApi
 */
@Ignore
public class SupportApiTest {

    private final SupportApi api = new SupportApi();

    
    /**
     * Creates and downloads a support zip
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void supportzipTest() throws Exception {
        SupportZipGeneratorRequest body = null;
        api.supportzip(body);

        // TODO: test validations
    }
    
    /**
     * Creates a support zip and returns the path
     *
     * 
     *
     * @throws Exception
     *          if the Api call fails
     */
    @Test
    public void supportzippathTest() throws Exception {
        SupportZipGeneratorRequest body = null;
        SupportZipXO response = api.supportzippath(body);

        // TODO: test validations
    }
    
}
